### ISSUE TITLE
Random strings?

### ISSUE THREAD

**Issue by ahmetb** [rjmax/ArmExamples#1]
Hi Ryan,

I was wondering if there's a way to create random strings or numbers in the templates. For instance I don't want to prompt users for a storage account name, and just want to create a storage account named `[concat('prefix', rand())]` which probably would be available. 

Any ideas?

**Comment by rjmax** [comment]
Templates must declare consistent goal state; running a template consecutively must result in the same outcome. Adding a rand() function would violate this principle.

As an alternative, what about generating the random string in the PS/cli script which executes the template, and then passing it in as a parameter?

**Comment by ahmetb** [comment]
Got it, thanks!

**Comment by rjmax** [comment]
FYI - check out the new uniqueString function; while not random (for the reasons mentioned previously,) I think it addresses your scenario.  It can generate a unique string for a sub, rg, or deployment (name).

https://github.com/rjmax/ArmExamples/blob/master/uniqueStringSample.json

**Comment by ahmetb** [comment]
![](http://i.giphy.com/xTiTnEqmOFXmlZVTbi.gif) thx
